package com.smartqurylys.backend.shared.enums;

public enum ActivityActionType {
    REQUEST_ACCEPTANCE,
    ACCEPTED_ACCEPTANCE,
    REJECTED_ACCEPTANCE,
    PROJECT_UPDATED,
    STAGE_UPDATED,
    STAGE_DELETED,
    FILE_ADDED,
    FILE_DELETED,
    DOCUMENT_ADDED,
    DOCUMENT_DELETED,
    PARTICIPANT_INVITED,
    PARTICIPANT_JOINED,
    PARTICIPANT_REMOVED
}
