package com.smartqurylys.backend.shared.enums;

public enum ActivityActionType {
    REQUEST_ACCEPTANCE,
    ACCEPTED_ACCEPTANCE,
    REJECTED_ACCEPTANCE,
    PROJECT_UPDATED,
    STAGE_CREATED,
    STAGE_UPDATED,
    STAGE_DELETED,
    TASK_CREATED,
    TASK_UPDATED,
    TASK_DELETED,
    TASK_STARTED,
    TASK_COMPLETION_REQUESTED,
    TASK_COMPLETION_APPROVED,
    TASK_COMPLETION_REJECTED,
    TASK_RETURNED_TO_WORK,
    TASK_COMMENT_ADDED,
    FILE_ADDED,
    FILE_DELETED,
    DOCUMENT_ADDED,
    DOCUMENT_DELETED,
    PARTICIPANT_INVITED,
    PARTICIPANT_JOINED,
    PARTICIPANT_REMOVED
}
