package com.smartqurylys.backend.shared.enums;

public enum Specialization {
    EARTHWORKS,
    FOUNDATION_WORKS,
    ROOFING_WORKS,
    DEMOLITION_WORKS,
    TURNKEY_COTTAGE_AND_VILLA_CONSTRUCTION,
    ELECTRICAL_INSTALLATION,
    PLUMBING_AND_SEWERAGE,
    VENTILATION_AND_AIR_CONDITIONING,
    PLASTERING_AND_PAINTING_WORKS,
    TILE_LAYING,
    LAMINATE_AND_PARQUET_LAYING,
    INTERIOR_FINISHING_WORKS,
    HIGH_QUALITY_FINE_FINISHING,
    HEATING_SYSTEM_INSTALLATION,
    LOW_CURRENT_SYSTEMS_INSTALLATION,
    FIRE_SAFETY_SYSTEM_INSTALLATION,
    WATERPROOFING_WORKS,
    INSTALLATION_OF_WINDOWS_DOORS_AND_PARTITIONS,
    LANDSCAPING_AND_GREENING_OF_THE_TERRITORY,
    ASPHALTING_OF_ROADS_AND_TERRITORIES,
    INSTALLATION_OF_CURBS_AND_ROAD_BARRIERS;


}