CREATE TYPE activity_action_type AS ENUM (
    'REQUEST_ACCEPTANCE', 'ACCEPTED_ACCEPTANCE', 'REJECTED_ACCEPTANCE', 
    'PROJECT_UPDATED', 'STAGE_UPDATED', 'STAGE_DELETED', 
    'FILE_ADDED', 'FILE_DELETED'
);

CREATE TYPE activity_entity_type AS ENUM ('PROJECT', 'STAGE', 'FILE', 'LICENSE');


CREATE TABLE IF NOT EXISTS public.activity_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action_type activity_action_type NOT NULL,
    actor_full_name character varying(255) NOT NULL,
    entity_id bigint NOT NULL,
    entity_name character varying(255) NOT NULL,
    entity_type activity_entity_type NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    actor_id bigint NOT NULL,
    project_id bigint NOT NULL,
    FOREIGN KEY (actor_id) REFERENCES public.users(id),
    FOREIGN KEY (project_id) REFERENCES public.projects(id)
);

ALTER TABLE public.activity_logs OWNER TO postgres;

INSERT INTO public.activity_logs
(id, action_type, actor_full_name, entity_id, entity_name, entity_type, "timestamp", actor_id, project_id)
VALUES
(3, 'FILE_ADDED', 'ТОО ''Строительные Технологии''', 50, 'image.png', 'FILE', '2025-08-01 20:55:16.576935', 17, 18),
(4, 'FILE_ADDED', 'ТОО ''Строительные Технологии''', 71, 'UserFlow.png', 'FILE', '2025-08-04 20:26:34.49736', 17, 18),
(5, 'PROJECT_UPDATED', 'ТОО ''Строительные Технологии''', 18, 'Обновленное имя', 'PROJECT', '2025-08-04 21:07:32.626056', 17, 18),
(14, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:43:07.323131', 13, 18),
(15, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:43:15.820332', 17, 18),
(16, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:45:53.552224', 17, 18),
(17, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:46:09.895672', 13, 18),
(18, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:48:41.582731', 17, 18),
(19, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:48:51.332922', 13, 18),
(20, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:48:55.448115', 17, 18),
(21, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:23.002414', 13, 18),
(22, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:35.107993', 17, 18),
(23, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:36.283573', 17, 18),
(24, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:36.720018', 17, 18),
(25, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:37.227951', 17, 18),
(26, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:37.658741', 17, 18),
(27, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:37.89311', 17, 18),
(28, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:38.089463', 17, 18),
(29, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:38.297343', 17, 18),
(30, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:50:38.935217', 17, 18),
(31, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 17:51:29.959668', 13, 18),
(32, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:34:04.959145', 17, 18),
(33, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:34:09.498554', 13, 18),
(34, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:34:16.720424', 17, 18),
(35, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:34:19.501518', 17, 18),
(36, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:34:23.180347', 17, 18),
(37, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:34:44.353657', 17, 18),
(38, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:35:00.598309', 17, 18),
(39, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:39:16.124623', 13, 18),
(40, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:39:27.023764', 17, 18),
(41, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:39:30.974905', 17, 18),
(42, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:42:34.788041', 13, 18),
(43, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:42:39.107811', 17, 18),
(44, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:42:43.084945', 17, 18),
(45, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:42:48.218617', 13, 18),
(46, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-11 18:42:53.174921', 17, 18),
(50, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-19 14:35:25.154546', 13, 18),
(51, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-19 14:35:33.205582', 17, 18),
(52, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-19 14:35:35.639995', 17, 18),
(53, 'REQUEST_ACCEPTANCE', 'Test User', 41, 'Новая Задача 3', 'PROJECT', '2025-08-19 15:07:52.918881', 13, 18),
(54, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-19 15:08:01.313549', 17, 18),
(55, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 41, 'Новая Задача 3', 'PROJECT', '2025-08-19 15:08:11.575813', 17, 18),
(56, 'PROJECT_UPDATED', 'ТОО ''Строительные Технологии''', 18, 'Обновленное имя', 'PROJECT', '2025-08-19 15:09:08.082891', 17, 18),
(57, 'FILE_ADDED', 'ТОО ''Строительные Технологии''', 91, 'UserFlow (4) (1).png', 'PROJECT', '2025-08-19 15:09:53.423552', 17, 18),
(58, 'PROJECT_UPDATED', 'ТОО ''Строительные Технологии''', 18, 'Обновленное имя', 'PROJECT', '2025-08-25 18:48:27.515207', 17, 18),
(59, 'FILE_ADDED', 'ТОО ''Строительные Технологии''', 93, 'UserFlow (4) (2).png', 'PROJECT', '2025-08-25 18:49:01.054903', 17, 18),
(60, 'REQUEST_ACCEPTANCE', 'Test User3', 42, 'test3', 'PROJECT', '2025-09-09 15:21:03.232078', 13, 18),
(61, 'REQUEST_ACCEPTANCE', 'Test User3', 50, 'test3', 'PROJECT', '2025-09-09 15:21:07.498072', 13, 18),
(62, 'REQUEST_ACCEPTANCE', 'Test User3', 40, 'Новая Задача 2', 'PROJECT', '2025-09-09 15:21:10.436598', 13, 18),
(63, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 40, 'Новая Задача 2', 'PROJECT', '2025-09-09 15:21:27.729123', 17, 18),
(64, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 42, 'test3', 'PROJECT', '2025-09-09 15:21:28.880285', 17, 18),
(65, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 50, 'test3', 'PROJECT', '2025-09-09 15:21:38.036954', 17, 18),
(66, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 42, 'test3', 'PROJECT', '2025-09-09 15:21:45.515671', 17, 18),
(67, 'REJECTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 50, 'test3', 'PROJECT', '2025-09-09 15:21:55.089185', 17, 18),
(68, 'FILE_ADDED', 'ТОО ''Строительные Технологии''', 94, 'UserFlow (1).png', 'PROJECT', '2025-09-28 21:29:31.888369', 17, 18),
(69, 'FILE_ADDED', 'ТОО ''Строительные Технологии''', 95, 'UserFlow (5).png', 'PROJECT', '2025-09-28 21:29:52.880046', 17, 18),
(70, 'FILE_ADDED', 'ТОО ''Строительные Технологии''', 96, 'Договор.png', 'PROJECT', '2025-09-28 21:30:33.259007', 17, 18),
(71, 'REQUEST_ACCEPTANCE', 'Test User3', 54, 'test', 'PROJECT', '2025-10-05 15:47:56.975008', 13, 18),
(72, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 54, 'test', 'PROJECT', '2025-10-05 15:48:28.329834', 17, 18),
(73, 'REQUEST_ACCEPTANCE', 'Test User3', 56, 'test3', 'PROJECT', '2025-10-05 15:49:11.117676', 13, 18),
(74, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 56, 'test3', 'PROJECT', '2025-10-05 15:49:23.715334', 17, 18),
(75, 'REQUEST_ACCEPTANCE', 'Test User3', 55, 'test2', 'PROJECT', '2025-10-05 15:50:43.66826', 13, 18),
(76, 'ACCEPTED_ACCEPTANCE', 'ТОО ''Строительные Технологии''', 55, 'test2', 'PROJECT', '2025-10-05 15:50:54.682571', 17, 18),
(83, 'REQUEST_ACCEPTANCE', 'Ilyas', 60, 'test', 'PROJECT', '2026-01-24 14:39:40.960785', 13, 18),
(98, 'REJECTED_ACCEPTANCE', 'Гедатсу Зор', 60, 'test', 'PROJECT', '2026-01-24 15:42:25.130683', 17, 18),
(99, 'REQUEST_ACCEPTANCE', 'Ilyas', 60, 'test', 'PROJECT', '2026-01-24 15:42:30.971697', 13, 18),
(100, 'REJECTED_ACCEPTANCE', 'Гедатсу Зор', 60, 'test', 'PROJECT', '2026-01-24 15:42:33.917664', 17, 18),
(101, 'REQUEST_ACCEPTANCE', 'Ilyas', 60, 'test', 'PROJECT', '2026-01-24 15:42:51.656566', 13, 18),
(102, 'ACCEPTED_ACCEPTANCE', 'Гедатсу Зор', 60, 'test', 'PROJECT', '2026-01-24 15:42:55.386339', 17, 18),
(103, 'FILE_ADDED', 'Гедатсу Зор', 103, 'ClassDiagramITM (1).png', 'PROJECT', '2026-02-01 19:12:57.596637', 17, 23),
(104, 'FILE_ADDED', 'Гедатсу Зор', 104, 'ClassDiagramITM (1).png', 'PROJECT', '2026-02-01 19:20:16.032986', 17, 23),
(105, 'PROJECT_UPDATED', 'admin', 18, 'Обновленное имя', 'PROJECT', '2026-02-02 20:30:24.188221', 18, 18),
(106, 'FILE_ADDED', 'Гедатсу Зор', 114, 'ClassDiagramITM (1) (1).png', 'PROJECT', '2026-02-04 14:16:47.188756', 17, 23)
ON CONFLICT (id) DO NOTHING;


SELECT pg_catalog.setval('public.activity_logs_id_seq', 106, true);
