CREATE TABLE IF NOT EXISTS public.document_constructor_templates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(120) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    category VARCHAR(120),
    description VARCHAR(500),
    version INTEGER NOT NULL DEFAULT 1,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_system BOOLEAN NOT NULL DEFAULT TRUE,
    schema_json TEXT NOT NULL,
    layout_json TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.document_constructor_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    template_id BIGINT NOT NULL REFERENCES public.document_constructor_templates(id),
    owner_user_id BIGINT NOT NULL REFERENCES public.users(id),
    title VARCHAR(255) NOT NULL,
    status VARCHAR(40) NOT NULL,
    template_name_snapshot VARCHAR(255) NOT NULL,
    template_version_snapshot INTEGER NOT NULL,
    form_data_json TEXT NOT NULL,
    rendered_html TEXT NOT NULL,
    validation_errors_json TEXT NOT NULL DEFAULT '[]',
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_document_constructor_documents_owner
    ON public.document_constructor_documents(owner_user_id, updated_at DESC);

INSERT INTO public.document_constructor_templates (
    code,
    name,
    category,
    description,
    version,
    is_active,
    is_system,
    schema_json,
    layout_json
) VALUES
(
    'construction-service-agreement',
    'Construction Service Agreement',
    'Contracts',
    'A fixed-structure agreement for construction or subcontracting work with optional payment and penalty clauses.',
    1,
    TRUE,
    TRUE,
    $$[
      {
        "key": "parties",
        "title": "Parties",
        "fields": [
          {"key": "contractDate", "label": "Contract date", "type": "date", "required": true},
          {"key": "customerCompany", "label": "Customer company", "type": "text", "required": true, "placeholder": "LLP Example Customer"},
          {"key": "contractorCompany", "label": "Contractor company", "type": "text", "required": true, "placeholder": "LLP Example Contractor"},
          {"key": "signatoryName", "label": "Authorized signatory", "type": "text", "required": true, "placeholder": "Full name"}
        ]
      },
      {
        "key": "scope",
        "title": "Scope",
        "fields": [
          {"key": "scopeOfWork", "label": "Scope of work", "type": "text", "required": true, "placeholder": "Facade installation and related finishing works"},
          {"key": "siteAddress", "label": "Site address", "type": "text", "required": true, "placeholder": "Project site address"},
          {"key": "completionDate", "label": "Completion date", "type": "date", "required": true},
          {"key": "warrantyPeriod", "label": "Warranty period", "type": "select", "required": true, "options": [
            {"value": "12 months", "label": "12 months"},
            {"value": "24 months", "label": "24 months"},
            {"value": "36 months", "label": "36 months"}
          ]}
        ]
      },
      {
        "key": "financials",
        "title": "Financials",
        "fields": [
          {"key": "contractAmount", "label": "Contract amount", "type": "money", "required": true},
          {"key": "paymentTerm", "label": "Payment terms", "type": "select", "required": true, "options": [
            {"value": "100% after acceptance", "label": "100% after acceptance"},
            {"value": "50% advance / 50% after acceptance", "label": "50% advance / 50% after acceptance"},
            {"value": "Monthly by completed volume", "label": "Monthly by completed volume"}
          ]},
          {"key": "includeAdvanceClause", "label": "Include advance payment clause", "type": "boolean", "required": false},
          {"key": "advancePayment", "label": "Advance payment amount", "type": "money", "required": true, "visibleWhen": "includeAdvanceClause"},
          {"key": "includePenaltyClause", "label": "Include delay penalty clause", "type": "boolean", "required": false},
          {"key": "penaltyRate", "label": "Penalty rate per day", "type": "text", "required": true, "visibleWhen": "includePenaltyClause", "placeholder": "0.1% of delayed amount"}
        ]
      }
    ]$$,
    $$[
      {
        "title": "Agreement Summary",
        "blocks": [
          {"type": "heading", "content": "Construction Service Agreement"},
          {"type": "paragraph", "content": "This Agreement is made on {{contractDate}} between {{customerCompany}} as the Customer and {{contractorCompany}} as the Contractor."},
          {"type": "paragraph", "content": "The Contractor shall perform {{scopeOfWork}} at {{siteAddress}} and complete the work by {{completionDate}}."}
        ]
      },
      {
        "title": "Commercial Terms",
        "blocks": [
          {"type": "paragraph", "content": "The total contract amount is {{contractAmount}}. Payment shall be made under the following terms: {{paymentTerm}}."},
          {"type": "paragraph", "content": "The Customer shall pay an advance of {{advancePayment}} within 3 business days after signing this Agreement.", "visibleWhen": "includeAdvanceClause"},
          {"type": "paragraph", "content": "If the Contractor delays performance, a penalty of {{penaltyRate}} applies for each day of delay.", "visibleWhen": "includePenaltyClause"}
        ]
      },
      {
        "title": "Final Provisions",
        "blocks": [
          {"type": "paragraph", "content": "The warranty period for the completed works is {{warrantyPeriod}} from the acceptance date."},
          {"type": "paragraph", "content": "This Agreement may be signed by the authorized representative {{signatoryName}} and becomes effective from the signing date."}
        ]
      }
    ]$$
),
(
    'work-completion-certificate',
    'Work Completion Certificate',
    'Certificates',
    'A concise acceptance certificate for confirming completed construction work and any remaining defects.',
    1,
    TRUE,
    TRUE,
    $$[
      {
        "key": "certificate",
        "title": "Certificate details",
        "fields": [
          {"key": "certificateNumber", "label": "Certificate number", "type": "text", "required": true, "placeholder": "WCC-2026-001"},
          {"key": "certificateDate", "label": "Certificate date", "type": "date", "required": true},
          {"key": "customerCompany", "label": "Customer company", "type": "text", "required": true},
          {"key": "contractorCompany", "label": "Contractor company", "type": "text", "required": true}
        ]
      },
      {
        "key": "work",
        "title": "Completed work",
        "fields": [
          {"key": "projectName", "label": "Project name", "type": "text", "required": true},
          {"key": "workPeriodStart", "label": "Work period start", "type": "date", "required": true},
          {"key": "workPeriodEnd", "label": "Work period end", "type": "date", "required": true},
          {"key": "completedWorkSummary", "label": "Completed work summary", "type": "text", "required": true, "placeholder": "Describe the accepted works"},
          {"key": "acceptedAmount", "label": "Accepted amount", "type": "money", "required": true}
        ]
      },
      {
        "key": "acceptance",
        "title": "Acceptance",
        "fields": [
          {"key": "defectsFound", "label": "Defects found", "type": "boolean", "required": false},
          {"key": "defectsDescription", "label": "Defects description", "type": "text", "required": true, "visibleWhen": "defectsFound", "placeholder": "List defects or punch items"},
          {"key": "receiverName", "label": "Receiving representative", "type": "text", "required": true}
        ]
      }
    ]$$,
    $$[
      {
        "title": "Certificate",
        "blocks": [
          {"type": "heading", "content": "Work Completion Certificate No. {{certificateNumber}}"},
          {"type": "paragraph", "content": "This certificate is issued on {{certificateDate}} by {{customerCompany}} to confirm that {{contractorCompany}} completed the agreed scope of work for {{projectName}}."}
        ]
      },
      {
        "title": "Accepted Works",
        "blocks": [
          {"type": "paragraph", "content": "The accepted work period covers {{workPeriodStart}} through {{workPeriodEnd}}."},
          {"type": "paragraph", "content": "Completed work summary: {{completedWorkSummary}}."},
          {"type": "paragraph", "content": "The total accepted amount is {{acceptedAmount}}."}
        ]
      },
      {
        "title": "Acceptance Result",
        "blocks": [
          {"type": "paragraph", "content": "Defects and punch items identified during acceptance: {{defectsDescription}}.", "visibleWhen": "defectsFound"},
          {"type": "paragraph", "content": "No material defects were identified during acceptance.", "visibleWhen": "!defectsFound"},
          {"type": "paragraph", "content": "The work is accepted by {{receiverName}}."}
        ]
      }
    ]$$
)
ON CONFLICT (code) DO NOTHING;
