CREATE TYPE notification_type AS ENUM (
    'INVITATION',
    'PROJECT_UPDATE',
    'FILE_UPLOAD',
    'TASK_ASSIGNMENT',
    'MENTION',
    'STAGE_REACTIVATION',
    'LICENSE_APPROVED',
    'LICENSE_REJECTED'
);



CREATE TABLE IF NOT EXISTS public.notifications (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone NOT NULL,
    is_read boolean NOT NULL,
    message character varying(255) NOT NULL,
    related_entity_id bigint,
    type notification_type NOT NULL,
    project_id bigint,
    recipient_id bigint NOT NULL,
    sender_id bigint,
    FOREIGN KEY (recipient_id) REFERENCES public.users(id) ON DELETE CASCADE,
    FOREIGN KEY (sender_id) REFERENCES public.users(id),
    FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE
);
ALTER TABLE public.notifications OWNER TO postgres;


