CREATE TABLE IF NOT EXISTS public.email_verification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    expiration_time timestamp(6) without time zone NOT NULL
);

ALTER TABLE public.email_verification OWNER TO postgres;

CREATE TABLE IF NOT EXISTS public.phone_verification (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code character varying(255) NOT NULL,
    expiration_time timestamp(6) without time zone NOT NULL,
    phone character varying(255) NOT NULL
);
ALTER TABLE public.phone_verification OWNER TO postgres;