ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'DOCUMENT_ADDED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'DOCUMENT_DELETED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'PARTICIPANT_INVITED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'PARTICIPANT_JOINED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'PARTICIPANT_REMOVED';

ALTER TYPE activity_entity_type ADD VALUE IF NOT EXISTS 'DOCUMENT';
ALTER TYPE activity_entity_type ADD VALUE IF NOT EXISTS 'PARTICIPANT';
