CREATE TABLE IF NOT EXISTS public.estimates (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    document_id BIGINT,
    overheads_amount real NOT NULL,
    reserve_amount real NOT NULL,
    transport_amount real NOT NULL,
    FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE
);
ALTER TABLE public.estimates OWNER TO postgres;




----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.estimate_item (
    id bigint NOT NULL,
    name character varying(255),
    quantity real NOT NULL,
    unit character varying(255),
    unit_price real NOT NULL,
    estimate_id integer,
    FOREIGN KEY (estimate_id) REFERENCES public.estimates(id) ON DELETE CASCADE
);
ALTER TABLE public.estimate_item OWNER TO postgres;


