CREATE TYPE project_task_board_status AS ENUM (
    'TODO',
    'IN_PROGRESS',
    'DONE',
    'BLOCKED'
);

CREATE TYPE project_task_board_priority AS ENUM (
    'LOW',
    'MEDIUM',
    'HIGH',
    'CRITICAL'
);

CREATE TABLE IF NOT EXISTS public.project_task_board_stages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL,
    name character varying(255) NOT NULL,
    position integer NOT NULL DEFAULT 0,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT fk_project_task_board_stage_project
        FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_project_task_board_stages_project_id
    ON public.project_task_board_stages(project_id);

CREATE TABLE IF NOT EXISTS public.project_task_board_tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint NOT NULL,
    stage_id bigint NOT NULL,
    parent_task_id bigint,
    title character varying(255) NOT NULL,
    description text,
    status project_task_board_status NOT NULL DEFAULT 'TODO',
    priority project_task_board_priority NOT NULL DEFAULT 'MEDIUM',
    due_date date,
    assignee_participant_id bigint,
    position integer NOT NULL DEFAULT 0,
    created_by_user_id bigint NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT fk_project_task_board_task_project
        FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE,
    CONSTRAINT fk_project_task_board_task_stage
        FOREIGN KEY (stage_id) REFERENCES public.project_task_board_stages(id) ON DELETE CASCADE,
    CONSTRAINT fk_project_task_board_task_parent
        FOREIGN KEY (parent_task_id) REFERENCES public.project_task_board_tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_project_task_board_task_assignee
        FOREIGN KEY (assignee_participant_id) REFERENCES public.participants(id) ON DELETE SET NULL,
    CONSTRAINT fk_project_task_board_task_creator
        FOREIGN KEY (created_by_user_id) REFERENCES public.users(id)
);

CREATE INDEX IF NOT EXISTS idx_project_task_board_tasks_project_id
    ON public.project_task_board_tasks(project_id);

CREATE INDEX IF NOT EXISTS idx_project_task_board_tasks_stage_id
    ON public.project_task_board_tasks(stage_id);

CREATE INDEX IF NOT EXISTS idx_project_task_board_tasks_parent_task_id
    ON public.project_task_board_tasks(parent_task_id);

CREATE INDEX IF NOT EXISTS idx_project_task_board_tasks_assignee_participant_id
    ON public.project_task_board_tasks(assignee_participant_id);

CREATE TABLE IF NOT EXISTS public.project_task_comments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id bigint NOT NULL,
    author_user_id bigint NOT NULL,
    message text NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    CONSTRAINT fk_project_task_comment_task
        FOREIGN KEY (task_id) REFERENCES public.project_task_board_tasks(id) ON DELETE CASCADE,
    CONSTRAINT fk_project_task_comment_author
        FOREIGN KEY (author_user_id) REFERENCES public.users(id)
);

CREATE INDEX IF NOT EXISTS idx_project_task_comments_task_id
    ON public.project_task_comments(task_id);
