ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'STAGE_CREATED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'TASK_CREATED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'TASK_UPDATED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'TASK_DELETED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'TASK_STARTED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'TASK_COMPLETION_REQUESTED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'TASK_COMPLETION_APPROVED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'TASK_COMPLETION_REJECTED';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'TASK_RETURNED_TO_WORK';
ALTER TYPE activity_action_type ADD VALUE IF NOT EXISTS 'TASK_COMMENT_ADDED';

ALTER TYPE activity_entity_type ADD VALUE IF NOT EXISTS 'TASK';
