CREATE TYPE license_review_status AS ENUM (
    'PENDING_REVIEW',
    'APPROVED',
    'REJECTED'
);

CREATE TABLE IF NOT EXISTS public.licenses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_id bigint NOT NULL,
    license_category_display character varying(255),
    review_status license_review_status,
    organisation_id bigint,
    rejection_reason character varying(500),
    FOREIGN KEY (organisation_id) REFERENCES public.organisations(id),
    Foreign Key (file_id) REFERENCES public.files(id)
);
ALTER TABLE public.licenses OWNER TO postgres;

INSERT INTO public.licenses 
(file_id, license_category_display, review_status, organisation_id, rejection_reason)
VALUES
(112, 'Лицензия', 'APPROVED', 39, NULL)
ON CONFLICT DO NOTHING;

