

CREATE TABLE IF NOT EXISTS public.files (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint,
    created_at timestamp(6) without time zone NOT NULL,
    filepath character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    size bigint NOT NULL,
    user_id bigint,
    schedule_id bigint,
    task_id bigint,
    document_id bigint,
    organisation_id bigint,
    file_type character varying(31) DEFAULT 'FILE'::character varying NOT NULL,
    FOREIGN KEY (task_id) REFERENCES public.tasks(id),
    FOREIGN KEY (user_id) REFERENCES public.users(id),
    FOREIGN KEY (schedule_id) REFERENCES public.schedules(id),
    FOREIGN KEY (project_id) REFERENCES public.projects(id),
    FOREIGN KEY (organisation_id) REFERENCES public.organisations(id),
    FOREIGN KEY (document_id) REFERENCES public.documents(id)
);

ALTER TABLE public.files OWNER TO postgres;

INSERT INTO public.files 
(id, project_id, created_at, filepath, name, size, user_id, schedule_id, task_id, document_id, organisation_id, file_type)
VALUES
(97, NULL, '2025-10-05 16:28:52.579201', 'uploads\\temp_1759663732572_96f9e1e7-8160-4531-afca-a18a6daa94a7.png', 'Договор (2).png', 430122, 17, NULL, 60, NULL, NULL, 'FILE'),
(98, NULL, '2025-10-05 16:30:22.872721', 'uploads\\temp_1759663822872_2748aef2-379b-48f0-b3e6-2b64cc3d86ad.png', 'Договор (2) (1).png', 430122, 17, NULL, NULL, NULL, NULL, 'FILE'),
(99, NULL, '2025-10-29 18:33:45.605094', 'uploads\\temp_1761744825589_326f8295-e5f0-44ab-8f1e-9d2b500a9133.png', '2012.png', 136583, 17, NULL, NULL, NULL, NULL, 'FILE'),
(101, NULL, '2026-01-25 13:23:58.338048', 'uploads\\temp_1769329438331_fd8ad4be-916a-4fb3-9058-426b9dafd272.png', 'ERD_IMAGE.png', 52507, 17, NULL, NULL, NULL, NULL, 'FILE'),
(102, NULL, '2026-01-25 13:52:36.533599', 'uploads\\temp_1769331156532_340e88d7-c2be-4e71-b1b5-ce80f4c80c6e.png', 'ClassDiagramITM.png', 59860, 17, NULL, NULL, NULL, NULL, 'FILE'),
(105, NULL, '2026-02-01 19:48:53.219489', 'uploads\\temp_1769957333218_3600708e-4733-446e-9b61-e524041c6689.torrent', '[DL] Resident Evil 4 [P] [RUS + ENG + 11 RUS + ENG + 7] (2023, Horror) (Build 11025382 + 25 DLC) [P2P] [rutracker-6370216] (1).torrent', 229726, 17, NULL, NULL, NULL, NULL, 'FILE'),
(96, 18, '2025-09-28 21:30:33.259007', 'uploads\\temp_1759077033251_b627add1-d9d2-412e-85a6-2bc20c341281.png', 'Договор.png', 430122, 17, NULL, NULL, NULL, NULL, 'FILE'),
(106, NULL, '2026-02-01 20:36:43.924464', 'uploads\\temp_1769960203920_ed677f1f-30a1-495f-bee2-9be57f65258e.png', 'ClassDiagramITM (1) (1).png', 59860, 17, NULL, NULL, NULL, NULL, 'FILE'),
(107, NULL, '2026-02-02 12:35:20.301078', 'uploads\\temp_1770017720293_9e814f98-a595-4a75-bf5a-3d0328139c15.png', 'ClassDiagramITM (1) (1).png', 59860, NULL, NULL, NULL, NULL, NULL, 'FILE'),
(109, NULL, '2026-02-02 20:01:00.191114', 'uploads\\temp_1770044460185_ca90bbfc-1ba8-4d44-995a-0a0207033b60.png', 'ClassDiagramITM (1).png', 59860, NULL, NULL, NULL, NULL, NULL, 'FILE'),
(111, NULL, '2026-02-02 20:17:42.915896', 'uploads\\temp_1770045462908_22599bfc-353f-42d4-a470-d62ca7bfb1b7.png', 'ClassDiagramITM (1).png', 59860, 39, NULL, NULL, NULL, NULL, 'FILE'),
(112, NULL, '2026-02-02 20:17:42.916811', 'uploads\\temp_1770045462908_22599bfc-353f-42d4-a470-d62ca7bfb1b7.png', 'ClassDiagramITM (1).png', 59860, 39, NULL, NULL, NULL, NULL, 'LICENSE'),
(113, NULL, '2026-02-02 21:05:57.034889', 'uploads\\temp_1770048357025_66113965-3133-426a-a9ee-34164a77496b.png', 'ClassDiagramITM (1) (1).png', 59860, 17, NULL, NULL, NULL, NULL, 'FILE'),
(115, NULL, '2026-02-04 14:21:00.683341', 'uploads\\temp_1770196860682_9815951a-08fa-4197-afa4-55d5501fe0da.png', 'ClassDiagramITM (1) (1) (2).png', 59860, 17, NULL, NULL, NULL, NULL, 'FILE'),
(100, NULL, '2025-10-29 18:33:45.615168', 'uploads\\temp_1770196860682_9815951a-08fa-4197-afa4-55d5501fe0da.png', 'Обновленная лицензия на строительство', 59860, 17, NULL, NULL, NULL, NULL, 'LICENSE')
ON CONFLICT DO NOTHING;


SELECT pg_catalog.setval('public.files_id_seq', 115, true);


CREATE TABLE IF NOT EXISTS public.requirements (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description character varying(255) NOT NULL,
    sample_file_id bigint,
    task_id bigint NOT NULL,
    FOREIGN KEY (sample_file_id) REFERENCES public.files(id),
    FOREIGN KEY (task_id) REFERENCES public.tasks(id)
);
ALTER TABLE public.requirements OWNER TO postgres;