CREATE TABLE IF NOT EXISTS public.users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email character varying(255) UNIQUE NOT NULL,
    full_name character varying(255) NOT NULL,
    iin_bin character varying(255) NOT NULL,
    organization character varying(255),
    password character varying(255) NOT NULL,
    phone character varying(255),
    city_id bigint,
    user_type character varying(31) DEFAULT 'USER'::character varying NOT NULL,
    role character varying(255) DEFAULT 'USER'::character varying NOT NULL,
    FOREIGN KEY (city_id) REFERENCES public.cities(id)
);

ALTER TABLE public.users OWNER TO postgres;


INSERT INTO public.users 
(id, email, full_name, iin_bin, organization, password, phone, city_id, user_type, role) VALUES
(24, 'updated.user@example.com', 'Обновленное Имя Пользователя', '100000000000', NULL, '$2a$10$sXZ4QeiNKb6/kEEsbnbote8CYB5sTCXWzf4s9NqTbeQQX0C7QNwqa', '77778889900', 2, 'USER', 'USER'),
(10, 'gkey2014@gmail.com', 'Test User2', '111111111112', 'TestOrg', '$2a$10$jOh.eg1BaocMKR5rUgc1XOGFsCvIPhRUV0ff9KSVb2QzXgQI5vShy', '+77011230001', 1, 'USER', 'USER'),
(35, 'new.user@example.com', 'Новый Пользователь', '100000000050', NULL, '$2a$10$4cxaoESuEz5M9NufZyyhuOJqg81Tz7DxhTz4yjHki1Fn7rKYKT0vi', '77001112233', 1, 'USER', 'USER'),
(36, 'contractor.test@example.com', 'Алиев Арман Бахытович', '990101456789', NULL, '$2a$10$nINwHP.kbe1wJw5J2/vcRu8qIN/8i0gmO/XYNOowU5.7/Rj6dzkQi', '+77019876543', 1, 'Organisation', 'USER'),
(11, 'newemail1@example.com', 'Ilyas Sarsenbai', '123456789012', 'SmartQurylys', '$2a$10$vvxul8n9YEivw1De4Rutvu12mdIgUA5Fk7JAtKDEfXwirZEFuRgd6', '+77011230003', 1, 'USER', 'USER'),
(13, 'i_sarsenbay@kbtu.kz', 'Ilyas', '111111111198', 'TestOrg', '$2a$10$X.04enEdh/IBXOZYnBPLgOqA7IXzTpwOCc7Xevg/Y/me2GI4m9W1S', '+77011230023', 49, 'USER', 'USER'),
(12, 'ilyas23@example.com', 'test65', '987654321098', 'NewOrg', '$2a$10$cqTQxobK7ApR9.1.Gb2BL.3PbM0/MJtQScykjErw/kj6mUjjb68/S', '+77000001122', 50, 'USER', 'USER'),
(18, 'admin@gmail.com', 'admin', '111111111199', NULL, '$2a$10$rsK9RW5p2RY7uEje6UIv8uiZCp8GA8bCr2cykNAPdwi93HxhqpeCu', '+77011230022', 50, 'USER', 'ADMIN'),
(39, 'baiangali12344321@gmail.com', 'fafa', '123145153245', 'тест', '$2a$10$J6OXXjRvnZw9ae5L1ArpBuCtNi1mxs0KMc/MN.aVrblarapxMF/lW', '5142413212', NULL, 'Organisation', 'USER'),
(17, 'updated.email@example.com', 'Гедатсу Зор', '123456789013', 'ТОО ''Строительные Технологии''', '$2a$10$7GLmoWzjdoEAnoFK5QEt1uS316cC7AxIRRrLihku2NbeAStSo0QaO', '77771234567', 4, 'Organisation', 'ADMIN')
ON CONFLICT DO NOTHING;


SELECT pg_catalog.setval('public.users_id_seq', 39, true);