CREATE TYPE project_status AS ENUM (
    'DRAFT',
    'WAITING',
    'ACTIVE',
    'ON_PAUSE',
    'COMPLETED',
    'CANCELLED'
);

CREATE TABLE IF NOT EXISTS public.projects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description character varying(255),
    name character varying(255) NOT NULL,
    type character varying(255),
    status project_status DEFAULT 'DRAFT'::project_status NOT NULL,
    start_date date,
    end_date date,
    city_id bigint,
    user_id bigint,
    FOREIGN KEY (city_id) REFERENCES public.cities(id),
    FOREIGN KEY (user_id) REFERENCES public.users(id)
);

ALTER TABLE public.projects OWNER TO postgres;


INSERT INTO public.projects (id, description, end_date, name, start_date, status, type, city_id, user_id) VALUES
(23, 'test', '2026-02-28', 'test', '2026-02-03', 'DRAFT', 'test', 22, 17),
(18, 'Новое описание', '2025-09-15', 'Обновленное имя', '2025-07-15', 'ACTIVE', 'Реконструкция', 23, 17);

SELECT pg_catalog.setval('public.projects_id_seq', 23, true);


----------------------
CREATE TABLE IF NOT EXISTS public.project_notes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content text NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    author_id bigint NOT NULL,
    project_id bigint NOT NULL,
    FOREIGN KEY (author_id) REFERENCES public.users(id),
    FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE
);

ALTER TABLE public.project_notes OWNER TO postgres;

INSERT INTO public.project_notes (id, content, created_at, author_id, project_id) VALUES
(1, 'тест', '2026-01-28 15:38:08.279339', 17, 18),
(2, 'тест2', '2026-01-28 15:38:20.336299', 17, 18),
(3, 'тест3', '2026-01-28 15:38:34.36189', 13, 18),
(5, 'тест', '2026-02-04 16:22:50.000803', 17, 23),
(6, 'тест', '2026-02-04 16:23:17.597183', 13, 18);

SELECT pg_catalog.setval('public.project_notes_id_seq', 6, true);

