CREATE TABLE IF NOT EXISTS public.participants (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    can_send_notifications boolean NOT NULL,
    can_upload_documents boolean NOT NULL,
    role character varying(255) NOT NULL,
    project_id bigint,
    user_id bigint,
    FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE,
    FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE
);

ALTER TABLE public.participants OWNER TO postgres;


INSERT INTO public.participants (id, can_send_notifications, can_upload_documents, role, project_id, user_id)
VALUES
(19, true, true, 'Подрядчик', 18, 13)
ON CONFLICT DO NOTHING;

SELECT pg_catalog.setval('public.participants_id_seq', 19, true);



-----------------------------------------
CREATE TABLE IF NOT EXISTS public.participant_invitations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accepted boolean NOT NULL,
    can_send_notifications boolean NOT NULL,
    can_upload_documents boolean NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    role character varying(255),
    project_id bigint,
    user_id bigint,
    sender_id bigint,
    FOREIGN KEY (sender_id) REFERENCES public.users(id),
    FOREIGN KEY (user_id) REFERENCES public.users(id),
    FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE
);

ALTER TABLE public.participant_invitations OWNER TO postgres;

INSERT INTO public.participant_invitations 
(id, accepted, can_send_notifications, can_upload_documents, created_at, expires_at, role, project_id, user_id, sender_id)
VALUES
(30, false, true, false, '2025-08-19 15:09:21.369038', '2025-08-22 15:09:21.369038', 'Подрядчик', 18, 10, NULL)
ON CONFLICT DO NOTHING;

SELECT pg_catalog.setval('public.participant_invitations_id_seq', 38, true);

