CREATE TYPE document_status AS ENUM (
    'WAITING',
    'CREATION',
    'APPROVAL',
    'SIGNATURE',
    'REGISTRATION',
    'IN_PROGRESS',
    'COMPLETED'
);

CREATE TABLE IF NOT EXISTS public.documents (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    project_id bigint,
    -- TODO: uploaded_by_user_id BIGINT,
    file_path character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    status document_status DEFAULT 'CREATION'::document_status NOT NULL,
    upload_date timestamp(6) without time zone NOT NULL,
    FOREIGN KEY (project_id) REFERENCES public.projects(id)
    -- TODO: FOREIGN KEY (uploaded_by_user_id) REFERENCES public,users(id)
);

ALTER TABLE public.documents OWNER TO postgres;

INSERT INTO public.documents (id, project_id, file_path, name, status, upload_date) VALUES 
(1, NULL, 'uploads/doc1.pdf', 'Документ №1', 'WAITING', '2025-06-29 19:17:42.81')
ON CONFLICT DO NOTHING;

SELECT pg_catalog.setval('public.documents_id_seq', 6, true);



----------------------------------------------
CREATE TABLE IF NOT EXISTS public.document_signed (
    document_id integer NOT NULL,
    participant_id bigint NOT NULL,
    FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE,
    FOREIGN KEY (participant_id) REFERENCES public.participants(id) ON DELETE CASCADE,
    PRIMARY KEY (document_id, participant_id)
);

ALTER TABLE public.document_signed OWNER TO postgres;


CREATE TABLE IF NOT EXISTS public.document_have_to_sign (
    document_id integer,
    participant_id bigint,
    FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE,
    FOREIGN KEY (participant_id) REFERENCES public.participants(id) ON DELETE CASCADE,
    PRIMARY KEY (document_id, participant_id)
);


-------------------------------------------
CREATE TABLE IF NOT EXISTS public.comment (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author character varying(255) NOT NULL,
    -- TODO: author_id BIGINT,
    text character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    document_id integer,
    FOREIGN KEY (document_id) REFERENCES public.documents(id) ON DELETE CASCADE
    -- FOREIGN KEY (author_id) REFERENCES public.users(id) ON DELETE CASCADE
);



ALTER TABLE public.comment OWNER TO postgres;
