CREATE TYPE stage_status AS ENUM (
    'WAITING',
    'ACTIVE',
    'ON_PAUSE',
    'COMPLETED'
);

CREATE TABLE IF NOT EXISTS public.stages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying(255) NOT NULL,
    description character varying(255),
    start_date date,
    end_date date,
    status stage_status DEFAULT 'WAITING'::stage_status NOT NULL,
    contractors character varying(255),
    resources character varying(255),
    schedule_id bigint NOT NULL,
    FOREIGN KEY (schedule_id) REFERENCES public.schedules(id) ON DELETE CASCADE
);


ALTER TABLE public.stages OWNER TO postgres;

INSERT INTO public.stages 
(id, contractors, description, end_date, name, resources, start_date, status, schedule_id)
VALUES
(18, NULL, 'Заливка бетона', '2025-08-31', '1-этап', NULL, '2025-08-20', 'ACTIVE', 17),
(34, NULL, '2', '2026-02-28', '1-этап', NULL, '2026-02-13', 'ACTIVE', 21),
(35, NULL, 't', '2026-02-28', 't', NULL, '2026-02-07', 'WAITING', 21),
(22, 'ТОО СтройСервис', 'Работы по расчистке и подготовкe', '2025-07-15', '3-этап', NULL, '2025-07-01', 'COMPLETED', 17),
(19, NULL, 'sdasdsl', '2025-08-29', '2-этап', NULL, '2025-08-25', 'ACTIVE', 17)
ON CONFLICT DO NOTHING;
