CREATE TABLE IF NOT EXISTS public.tasks (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description character varying(255),
    end_date date,
    executed boolean NOT NULL,
    execution_requested boolean NOT NULL,
    info character varying(255),
    is_priority boolean NOT NULL,
    name character varying(255) NOT NULL,
    start_date date,
    participant_id bigint,
    stage_id bigint NOT NULL,
    FOREIGN KEY (participant_id) REFERENCES public.participants(id),
    FOREIGN KEY (stage_id) REFERENCES public.stages(id) ON DELETE CASCADE
);

ALTER TABLE public.tasks OWNER TO postgres;


INSERT INTO public.tasks 
(id, description, end_date, executed, execution_requested, info, is_priority, name, start_date, participant_id, stage_id)
VALUES
(58, 'test', '2025-10-19', FALSE, FALSE, NULL, FALSE, 'test3', '2025-10-12', NULL, 19),
(59, 'test', '2025-10-19', FALSE, FALSE, NULL, FALSE, 'test2', '2025-10-12', NULL, 19),
(61, 'еые', '2025-10-22', FALSE, FALSE, NULL, TRUE, 'test2', '2025-10-12', NULL, 18),
(43, 'test', '2025-08-31', FALSE, FALSE, NULL, FALSE, 'test', '2025-08-15', NULL, 22),
(62, 'е', '2025-10-17', FALSE, FALSE, NULL, FALSE, 'test3', '2025-10-05', NULL, 18),
(60, 'Описание задачи', '2025-07-05', TRUE, TRUE, 'Доп. информация', TRUE, 'Тестовая задача2', '2025-07-01', NULL, 18),
(63, 'п', '2026-02-08', FALSE, FALSE, NULL, FALSE, 'п', '2026-02-22', NULL, 34),
(66, 'f', '2026-02-28', FALSE, FALSE, NULL, FALSE, 'f', '2026-02-15', NULL, 34),
(67, 'и', '2026-02-18', FALSE, FALSE, NULL, FALSE, 'test', '2026-02-22', NULL, 34),
(57, 'test', '2025-10-16', FALSE, FALSE, NULL, FALSE, 'test', '2025-10-05', NULL, 19);



-----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.task_responsible_persons (
    task_id BIGINT,
    participant_id bigint,
    PRIMARY KEY (task_id, participant_id),
    FOREIGN KEY (participant_id) REFERENCES public.participants(id),
    FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE
);

ALTER TABLE public.task_responsible_persons OWNER TO postgres;

INSERT INTO public.task_responsible_persons (task_id, participant_id)
VALUES (60, 19);



-----------------------------------------------------
CREATE TABLE IF NOT EXISTS public.task_dependencies (
    task_id bigint,
    depends_on_task_id bigint,
    PRIMARY KEY (task_id, depends_on_task_id),
    FOREIGN KEY (task_id) REFERENCES public.tasks(id) ON DELETE CASCADE,
    FOREIGN KEY (depends_on_task_id) REFERENCES public.tasks(id) ON DELETE CASCADE
);

INSERT INTO public.task_dependencies (task_id, depends_on_task_id)
VALUES 
(61, 60),
(62, 61),
(62, 60);


ALTER TABLE public.task_dependencies OWNER TO postgres;


