CREATE TABLE IF NOT EXISTS public.schedules (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    project_id bigint,
    FOREIGN KEY (project_id) REFERENCES public.projects(id) ON DELETE CASCADE
);

ALTER TABLE public.schedules OWNER TO postgres;

INSERT INTO public.schedules 
(id, created_at, name, project_id)
VALUES
(17, '2025-08-01 20:56:26.999477', 'Название', 18),
(21, '2026-02-01 19:12:33.761762', 'ГПР', 23);
