CREATE TYPE organisation_specialization AS ENUM (
    'EARTHWORKS',
    'FOUNDATION_WORKS',
    'ROOFING_WORKS',
    'DEMOLITION_WORKS',
    'TURNKEY_COTTAGE_AND_VILLA_CONSTRUCTION',
    'ELECTRICAL_INSTALLATION',
    'PLUMBING_AND_SEWERAGE',
    'VENTILATION_AND_AIR_CONDITIONING',
    'PLASTERING_AND_PAINTING_WORKS',
    'TILE_LAYING',
    'LAMINATE_AND_PARQUET_LAYING',
    'INTERIOR_FINISHING_WORKS',
    'HIGH_QUALITY_FINE_FINISHING',
    'HEATING_SYSTEM_INSTALLATION',
    'LOW_CURRENT_SYSTEMS_INSTALLATION',
    'FIRE_SAFETY_SYSTEM_INSTALLATION',
    'WATERPROOFING_WORKS',
    'INSTALLATION_OF_WINDOWS_DOORS_AND_PARTITIONS',
    'LANDSCAPING_AND_GREENING_OF_THE_TERRITORY',
    'ASPHALTING_OF_ROADS_AND_TERRITORIES',
    'INSTALLATION_OF_CURBS_AND_ROAD_BARRIERS'
);

CREATE TYPE organisation_status AS ENUM (
    'AVAILABLE',
    'BUSY'
);

CREATE TYPE organisation_type AS ENUM (
    'CUSTOMER',
    'CONTRACTOR',
    'AUTHOR_SUPERVISON',
    'TECHNICAL_SUPERVISON',
    'SUPPLIER'
);


CREATE TABLE IF NOT EXISTS public.organisations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    field character varying(255),
    jud_address character varying(255),
    organization character varying(255) NOT NULL,
    "position" character varying(255),
    -- specialization varchar(255) NOT NULL,
    type organisation_type,
    years_of_experience bigint,
    status organisation_status,
    FOREIGN KEY (id) REFERENCES public.users(id)
);

ALTER TABLE public.organisations OWNER TO postgres;

INSERT INTO public.organisations 
(id, field, jud_address, organization, "position", type, years_of_experience, status)
VALUES
(36, 'Гражданское строительство', 'г. Алматы, пр. Абая 15', 'ТОО "СтройПлюс"', 'Главный инженер', 'CONTRACTOR', 10, NULL),
(17, 'Строительство', 'г. Алматы, ул. Абая, 100', 'ТОО ''Строительные Технологии''', 'Исполнительный директор', 'CONTRACTOR', 20, NULL),
(39, 'dr', 'syfa', 'TOO mydre', 'dre', 'CUSTOMER', 3, 'AVAILABLE')
ON CONFLICT DO NOTHING;

SELECT pg_catalog.setval('public.organisations_id_seq', 39, true);



------------------------------
CREATE TABLE IF NOT EXISTS public.organisation_specializations (
    organisation_id bigint,
    specialization organisation_specialization,
    PRIMARY KEY (organisation_id, specialization),
    FOREIGN KEY (organisation_id) REFERENCES public.organisations(id) ON DELETE CASCADE
);

ALTER TABLE public.organisation_specializations OWNER TO postgres;

INSERT INTO public.organisation_specializations 
(organisation_id, specialization)
VALUES
(36, 'ROOFING_WORKS'),
(36, 'PLASTERING_AND_PAINTING_WORKS'),
(36, 'FOUNDATION_WORKS'),
(39, 'INSTALLATION_OF_CURBS_AND_ROAD_BARRIERS'),
(39, 'TURNKEY_COTTAGE_AND_VILLA_CONSTRUCTION'),
(39, 'PLASTERING_AND_PAINTING_WORKS'),
(39, 'DEMOLITION_WORKS'),
(17, 'EARTHWORKS'),
(17, 'TILE_LAYING')
ON CONFLICT DO NOTHING;
