export enum ActivityActionType {
  REQUEST_ACCEPTANCE = 'REQUEST_ACCEPTANCE',
  ACCEPTED_ACCEPTANCE = 'ACCEPTED_ACCEPTANCE',
  REJECTED_ACCEPTANCE = 'REJECTED_ACCEPTANCE',
  PROJECT_UPDATED = 'PROJECT_UPDATED',
  STAGE_CREATED = 'STAGE_CREATED',
  STAGE_UPDATED = 'STAGE_UPDATED',
  STAGE_DELETED = 'STAGE_DELETED',
  TASK_CREATED = 'TASK_CREATED',
  TASK_UPDATED = 'TASK_UPDATED',
  TASK_DELETED = 'TASK_DELETED',
  TASK_STARTED = 'TASK_STARTED',
  TASK_COMPLETION_REQUESTED = 'TASK_COMPLETION_REQUESTED',
  TASK_COMPLETION_APPROVED = 'TASK_COMPLETION_APPROVED',
  TASK_COMPLETION_REJECTED = 'TASK_COMPLETION_REJECTED',
  TASK_RETURNED_TO_WORK = 'TASK_RETURNED_TO_WORK',
  TASK_COMMENT_ADDED = 'TASK_COMMENT_ADDED',
  FILE_ADDED = 'FILE_ADDED',
  FILE_DELETED = 'FILE_DELETED',
  DOCUMENT_ADDED = 'DOCUMENT_ADDED',
  DOCUMENT_DELETED = 'DOCUMENT_DELETED',
  PARTICIPANT_INVITED = 'PARTICIPANT_INVITED',
  PARTICIPANT_JOINED = 'PARTICIPANT_JOINED',
  PARTICIPANT_REMOVED = 'PARTICIPANT_REMOVED'
}

export enum ActivityEntityType {
  PROJECT = 'PROJECT',
  STAGE = 'STAGE',
  TASK = 'TASK',
  FILE = 'FILE',
  DOCUMENT = 'DOCUMENT',
  PARTICIPANT = 'PARTICIPANT'
}
