export enum ActivityActionType {
    REQUEST_ACCEPTANCE = "REQUEST_ACCEPTANCE",
    ACCEPTED_ACCEPTANCE = "ACCEPTED_ACCEPTANCE",
    REJECTED_ACCEPTANCE = "REJECTED_ACCEPTANCE",
    PROJECT_UPDATED = "PROJECT_UPDATED",
    STAGE_UPDATED = "STAGE_UPDATED",
    STAGE_DELETED = "STAGE_DELETED",
    FILE_ADDED = "FILE_ADDED",
    FILE_DELETED = "FILE_DELETED",
}

export enum ActivityEntityType {
    PROJECT = "PROJECT",
    STAGE = "STAGE",
    FILE = "FILE"
}